### ISSUE TITLE
Not work for /brainly

### ISSUE THREAD

**Issue by StephanieAgatha** [diosamuel/Virdina-Brainly#4]
/brainly ga bisa digunakan

**Comment by diosamuel** [comment]
> /brainly ga bisa digunakan

boleh dishare screenshot errornya?

**Comment by StephanieAgatha** [comment]
![Capture](https://user-images.githubusercontent.com/62786809/93176497-8a253400-f75b-11ea-89c7-0582e339f623.PNG)
cuma /brainly doang yang error

**Comment by diosamuel** [comment]
coba clone lagi
