### ISSUE TITLE
jawaban nyasar ke grup lain

### ISSUE THREAD

**Issue by ghost** [diosamuel/Virdina-Brainly#5]
pas command /brainly jawabannya malah nyasar ke grup lain

**Comment by diosamuel** [comment]
boleh di ss?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/68042984/93694281-f628e300-fb33-11ea-9762-023a169ea69d.png)

itu pertanyaannya di grup lain tapi malah nyasar

**Comment by diosamuel** [comment]
coba di clone lagi repo ini

**Comment by fdciabdul** [comment]
ini karna request dan koneksinya tidak sesuai , request double dan koneksi lambat

**Comment by diosamuel** [comment]
> ini karna request dan koneksinya tidak sesuai , request double dan koneksi lambat

iya, jadi balapan gitu, yang duluan yang dikirim, apakah mas punya solusi?

**Comment by fdciabdul** [comment]
coba pake fungsi msg.from aja jangan pake reply 


<a href="https://github.com/pedroslopez/whatsapp-web.js/blob/502b22f6d700110fcaa323d857686219ea0db9b6/src/structures/Message.js#L171">#L71</a>

**Comment by diosamuel** [comment]
> coba pake fungsi msg.from aja jangan pake reply 
> 
> 
> <a href="https://github.com/pedroslopez/whatsapp-web.js/blob/502b22f6d700110fcaa323d857686219ea0db9b6/src/structures/Message.js#L171">#L71</a>

function ```msg.from``` itu yang mana ya mas? saya cari di link tsb tidak ada

**Comment by diosamuel** [comment]
> > > coba pake fungsi msg.from aja jangan pake reply
> > > [#L71](https://github.com/pedroslopez/whatsapp-web.js/blob/502b22f6d700110fcaa323d857686219ea0db9b6/src/structures/Message.js#L171)
> > 
> > function `msg.from` itu yang mana ya mas? saya cari di link tsb tidak ada
> 
> pake sendMessage biasa. nggak pake reply, memang di beberapa hal, kadang suka random message apalagi kalo udah getgrup. 

ohh iya mas saya sudah pakai `client.sendMessage()`

Itu isi dari `Virdina.replyMessage()` sebenarnya `client.sendMessage()` mas cuman saya namainnya `replyMessage` 😅

**Comment by diosamuel** [comment]
> > > > coba pake fungsi msg.from aja jangan pake reply
> > > > [#L71](https://github.com/pedroslopez/whatsapp-web.js/blob/502b22f6d700110fcaa323d857686219ea0db9b6/src/structures/Message.js#L171)
> > > 
> > > function `msg.from` itu yang mana ya mas? saya cari di link tsb tidak ada
> > 
> > pake sendMessage biasa. nggak pake reply, memang di beberapa hal, kadang suka random message apalagi kalo udah getgrup. 
> 
> ohh iya mas saya sudah pakai `client.sendMessage`,

Itu isi dari `Virdina.replyMessage()` sebenarnya `client.sendMessage()` mas cuman saya namainnya `replyMessage()` 😅

**Comment by fdciabdul** [comment]
> > > > coba pake fungsi msg.from aja jangan pake reply
> > > > [#L71](https://github.com/pedroslopez/whatsapp-web.js/blob/502b22f6d700110fcaa323d857686219ea0db9b6/src/structures/Message.js#L171)
> > > 
> > > 
> > > function `msg.from` itu yang mana ya mas? saya cari di link tsb tidak ada
> > 
> > 
> > pake sendMessage biasa. nggak pake reply, memang di beberapa hal, kadang suka random message apalagi kalo udah getgrup.
> 
> ohh iya mas saya sudah pakai `client.sendMessage()`
> 
> Itu isi dari `Virdina.replyMessage()` sebenarnya `client.sendMessage()` mas cuman saya namainnya `replyMessage` 😅

tapi itu di ss an nya nge reply lho 🤔

**Comment by fdciabdul** [comment]
```
Virdina.replyMessage(msg.from , ` text `);
```

coba aja gitu

**Comment by diosamuel** [comment]
> > > > > coba pake fungsi msg.from aja jangan pake reply
> > > > > [#L71](https://github.com/pedroslopez/whatsapp-web.js/blob/502b22f6d700110fcaa323d857686219ea0db9b6/src/structures/Message.js#L171)
> > > > 
> > > > 
> > > > function `msg.from` itu yang mana ya mas? saya cari di link tsb tidak ada
> > > 
> > > 
> > > pake sendMessage biasa. nggak pake reply, memang di beberapa hal, kadang suka random message apalagi kalo udah getgrup.
> > 
> > ohh iya mas saya sudah pakai `client.sendMessage()`
> > 
> > Itu isi dari `Virdina.replyMessage()` sebenarnya `client.sendMessage()` mas cuman saya namainnya `replyMessage` 😅
> 
> tapi itu di ss an nya nge reply lho 🤔

iya mas makanya itu saya suruh clone ulang, karna saya sudah ganti kodenya jadi client.sendMessage()
