### ISSUE TITLE
EROR

### ISSUE THREAD

**Issue by MSI0072** [diosamuel/Virdina-Brainly#6]
![image](https://user-images.githubusercontent.com/63404067/93726823-9d932d80-fba7-11ea-8fab-7e7baa945688.png)

Permisi ini kenapa ya

**Comment by MSI0072** [comment]
Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md

**Comment by diosamuel** [comment]
udah fix?
