### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by MSI0072** [diosamuel/Virdina-Brainly#7]
![Screenshot_20200921-084147_WhatsApp](https://user-images.githubusercontent.com/63404067/93727664-52e4d600-fbe6-11ea-83e4-606a9244702a.jpg)

Not working

**Comment by diosamuel** [comment]
coba clone lagi

**Comment by KagChi** [comment]
khusus ip indo ya

**Comment by KagChi** [comment]
ip luar gabisa karena terblock captcha cloudflare

**Comment by fdciabdul** [comment]
> coba clone lagi

Scraping nya pakai PHP > Up ke hostingan  dibikin rest API
